### ISSUE TITLE
docs: Grammar, Typos and Small additions to Text

### ISSUE THREAD

**Issue by SheppardTri** [nent/nent#201]
**nent.dev page (Pre-name input)**

**"Data Extension" heading**
"Optional enhancements elements" should be 
"Optional enhancement elements"

**"Element Extension" heading**
"Special Attributes for Conditional on Any Element" should be 
"Special Attributes for Conditionals on Any Element"
_________________________________

**Get started/ installation page
"Installation" heading**
"To install these component" should be
"To install these components" 
_________________________________

**App Elements/ Theming page
"Native Dark Mode" heading**
"Once they've ussd the switch" should be 
"Once they've used the switch"

**"Theme Selection" heading**
"You can use also add your own icons or control to stye your dark-mode switch." should be 
"You can also add your own icons or control to change the style of your dark-mode switch."

**"Theme Selection" heading**
"There's also a switch change it:" should be
"There's also a switch to change it:"

**App Elements/ Native Sharing page
"Share Like an App" heading**
"This element taps into to the API" should be
"This element taps into the API" 

**App Elements/ Analytics page
"Application Analytics" heading**
"The < n-app-analytics > component"  should be
"The < n-app-analytics > element"
_________________________________

**Actions page
"Custom Actions" heading**
"through the n-app component." should be
"through the n-app element."

**Actions / Action Activations / Element Activations page
"Element Activated Actions" heading**
"Element activation works by attaching an event-listener to specified element." should be
"Element activation works by attaching an event-listener to a specified element."

**"Wrapped Input" heading**
default input text says "I am message you can change!" should be 
"I am a message you can change!"
_________________________________

**Routing/ Lazy Loaded page
"Lazy Loaded Routes" heading**
" without the need for a application-server," should be 
" without the need for an application-server,"

**"Lazy Route Example" heading**
" <n-view> or <n-view-prompt> components" should be
" <n-view> or <n-view-prompt> elements"

**"Lazy Content" heading**
" <n-content> or <n-content-markdown> components" should be
" <n-content> or <n-content-markdown> elements"
**also**
" defer-load attribute from child components" should be
" defer-load attribute from child elements"

**Routing/ Data Routes page
"How it works" heading**
"to provide data-driven views You can even use that data in your HTML, again with no code." should be 
"to provide data-driven views. You can even use that data in your HTML, again with no code."

**Data Route: Cake/Wine/Custom Item pages**
HTML sample code doesn't match page, particularly
```<p>Excellent choice, {{storage:name}}.</p>``` 
isn't seen on screen.

**Routing/ navigation/ guided/ tutorial page
"Example: Sub Route Required w/Multiple Data Conditions" heading**
"Now let’s move out of theory any into our new HTML Elements." should be 
"Now let’s move out of theory and into our new HTML Elements."

**Routing/ Data Provider page
"Installation" heading**
"the component <n-views>." should be
"the element <n-views>."
_________________________________

**Content page
"Data-Driven Content" heading**
"Conditional Rendering" is a dead link "Page not found".

**Content/ Partials page
"Include Remote HTML" heading**
"If the same HTML is exists in more than one place, you'll want to manage it in a singe place." should be 
"If the same HTML exists in more than one place, you'll want to manage it in a single place."
**also**
" <n-content> component." should be
" <n-content> element."

**"Guarantee Dependency References" heading**
" <n-content-reference> component" should be
" <n-content-reference> element"

**Content/ Markdown page**
Button says "Learn Markdown in 60 Second" should be "Learn Markdown in 60 Seconds"

**How it Works heading**
" <n-content-markdown> component." should be
" <n-content-markdown> element."

**Content/ Animated Reveal page**
"Somethings, just need to be extra." should be 
"Some things, just need to be extra."
_________________________________

**Audio page
"Rules" heading**
"the looping audio should stop and allowing the queued audio to play when it ends." should be 
"the looping audio should stop, allowing the queued audio to play when it ends."

**"Enable Audio" heading**
"you must first add the <n-audio> to the page." should be 
"you must first add the <n-audio> element to the page."

**Audio/ Controls page
"Control with Actions" heading**
" <n-action-activator> with the <n-audio-action-music> components." should be
" <n-action-activator> with the <n-audio-action-music> elements."

**Audio/ Music page
"Load Music" heading**
"Just include a <n-audio-action-music-load>" should be 
"Just include an <n-audio-action-music-load>"

**Audio/ Sounds page
"Then: Activate" heading**
"We play the sound by sending an action with start command." should be 
"We play the sound by sending an action with the start command."

**Audio/ Music & Sound page
"First: Load Music & Sounds" heading**
"<n-audio-action-sound-load> and <n-audio-action-music-load> components" should be
"<n-audio-action-sound-load> and <n-audio-action-music-load> elements"

**Audio/ Timed Sound page
"First: Preload" heading**
"using the <n-audio-action-sound-load> component." should be
"using the <n-audio-action-sound-load> element."

**"Then: Activate by Time" heading**
"We use the <n-action-activator> element and <n-audio-action-sound> elements" should be
"We use the <n-action-activator> and <n-audio-action-sound> elements"

**Audio/ Data Provider page
"Installation" heading**
"using the audio component <n-audio>" should be
"using the audio element <n-audio>"
**also**
"Add the `data-provider attribute to turn it on." is this missing markdown?
_________________________________

**Data Extension page
"How it works" heading**
"<n-data> component" should be
"<n-data> element"
**also**
"Once enabled data can be injected in HTML using tokens:" should be
"Once enabled, data can be injected in HTML using tokens:"

**"Custom Provider" heading**
" n-data component." should be
" n-data element."
_________________________________

**Elements Extension page
"How it works" heading**
"The <n-elements> component" should be
"The <n-elements> element" exception since "element" is said 3 times in the sentence?
_________________________________

**Comment by Logrythmik** [comment]
THANK YOU!!
