### ISSUE TITLE
routing issues when using root slashes

### ISSUE THREAD

**Issue by Logrythmik** [nent/nent#272]
**Description**
Given the following HTML, paths don't seem to get created correctly.  
```
 <n-view path="/nest"
    page-title="Fun"
    content-src="/pages/nest/fun.html">
     <n-view path="/more-fun"
          page-title="More Fun">
         <div>Child page</div>
     </n-view>
    <div slot="content">
      <a href="more-fun">This should work!</a>
    </div>
 </n-view>
```
Issues:

- Child a tag doesn't automatically get the parent path added to it
- Slashes in the root paths break SPA routing

**Comment by SheppardTri** [comment]
Issue resolved and slashes are functioning as normal again in original tested area.
